# Generated by Django 5.0 on 2024-01-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lider',
            name='ativo',
        ),
    ]
