# Generated by Django 4.2.1 on 2024-01-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiderModel',
            new_name='Usuarios',
        ),
    ]
