# Generated by Django 4.2.1 on 2024-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_lidermodel_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
