# Generated by Django 5.0 on 2024-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_lider_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
