# Generated by Django 4.2.1 on 2024-01-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_reunioes_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(default='Colaborador', max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(default='Líder', max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Reunioes',
        ),
    ]
