# Generated by Django 4.2.1 on 2024-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lider', models.CharField(max_length=255)),
                ('id_colaborador', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
