# Generated by Django 4.2.1 on 2024-01-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_colaboradores_lideres_delete_reunioes'),
        ('reunioes', '0002_alter_reuniao_id_colaborador_alter_reuniao_id_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='id_lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.lideres'),
        ),
    ]
